# Generated by Django 5.2.5 on 2026-04-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='generatedfood',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='user',
            new_name='profile',
        ),
    ]
